### ISSUE TITLE
Website is slow

### ISSUE THREAD

**Issue by abhibhanderii** [stackup-dev/open-source-campaign#288]
**Name of Proposer**
Developer

**Is your feature request related to a problem? Please describe.**
-- Every page on the website is loading slow, please improve the speed of loading data. 

**Describe the solution you'd like**
-- Either make your website lightweight or check the query of your database. 

**Describe alternatives you've considered**
-- I don't find any alternatives related to my problem.

**Additional context**
-- I don't have any screenshots.

**Comment by Developer404Solver** [comment]
Name of Proposer
Developer

This issue is as same as I want to say to StackUp team. I'm also suggesting for this issue in StackUp.
