### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by Patty258** [stackup-dev/open-source-campaign#299]
**Name of Proposer**
Lucas

**Is your feature request related to a problem? Please describe.**
I'm always to this feature to each quest to provide tutorial.

**Describe the solution you'd like**
It means to start quest to see video tutorial of quest.

**Describe alternatives you've considered**
no word.

**Comment by Lucas035** [comment]
> **Name of Proposer** Lucas
> 
> **Is your feature request related to a problem? Please describe.** I'm always to this feature to each quest to provide tutorial.
> 
> **Describe the solution you'd like** It means to start quest to see video tutorial of quest.
> 
> **Describe alternatives you've considered** no word.
